/**
 * AquaTerra Sitemap Generator
 * Run: node scripts/generate-sitemap.mjs
 *
 * Fetches project slugs + blog slugs from Supabase (public read-only CMS)
 * and writes a complete sitemap.xml to public/sitemap.xml
 */

import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))

// ── Config ──────────────────────────────────────────────────────────────────
const BASE_URL = 'https://www.ngoaquaterra.com'
const OUT_PATH = join(__dir, '../public/sitemap.xml')

// Public CMS Supabase (welfare projects + blogs — read-only, no auth needed)
const CMS_URL  = 'https://nurtpdbqfizmqtztmiwk.supabase.co'
const CMS_KEY  = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51cnRwZGJxZml6bXF0enRtaXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjE1NDQsImV4cCI6MjA5MTAzNzU0NH0.v-clxVi6B-tqQz8508ic4DwwQVPH0cUjhZJjtkdKwYA'

// ── Static routes ────────────────────────────────────────────────────────────
const STATIC = [
  // Core
  { path: '/',                  changefreq: 'daily',   priority: '1.0' },
  // Main sections
  { path: '/projects',          changefreq: 'weekly',  priority: '0.9' },
  { path: '/blog',              changefreq: 'weekly',  priority: '0.9' },
  { path: '/about',             changefreq: 'monthly', priority: '0.9' },
  { path: '/everything-we-do',  changefreq: 'monthly', priority: '0.9' },
  // Conversion
  { path: '/volunteer/apply',   changefreq: 'monthly', priority: '0.8' },
  { path: '/volunteer',         changefreq: 'monthly', priority: '0.8' },
  { path: '/collaborations',    changefreq: 'monthly', priority: '0.8' },
  { path: '/support',           changefreq: 'monthly', priority: '0.8' },
  { path: '/opportunities',     changefreq: 'weekly',  priority: '0.8' },
  // Secondary
  { path: '/contact',           changefreq: 'monthly', priority: '0.7' },
  { path: '/faq',               changefreq: 'monthly', priority: '0.7' },
  { path: '/schools',           changefreq: 'monthly', priority: '0.6' },
  { path: '/classes',           changefreq: 'monthly', priority: '0.6' },
]

// Known blog slugs (v1 site + any hardcoded ones)
const KNOWN_BLOG_SLUGS = [
  'welcome-to-blogs',
  'dynamics',
  'he-barks-i-heal',
  'art-of-empathy-(noun)',
  'voicing-one-s-opinions',
  'before-you-judge-read-this',
  'syntax-error',
  'a-cup-of-tea',
  'vibe-reviewing-booktok-s-answer-to-declining-imagery',
  'the-art-of-nostalgia-heartbreak',
  'pebbles-and-peaks',
  'people-in-the-mirror',
  'letter-to-my-city',
]

// ── Helpers ──────────────────────────────────────────────────────────────────
function url(path, changefreq = 'monthly', priority = '0.5') {
  return [
    '  <url>',
    `    <loc>${BASE_URL}${path}</loc>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n')
}

// ── Main ─────────────────────────────────────────────────────────────────────
async function generate() {
  const cms = createClient(CMS_URL, CMS_KEY)

  console.log('Fetching project slugs…')
  const { data: projects, error: projErr } = await cms
    .from('welfare_projects')
    .select('slug')
    .eq('is_draft', false)
    .order('workshop_date', { ascending: true })

  if (projErr) console.warn('Could not fetch projects:', projErr.message)

  console.log(`Found ${projects?.length ?? 0} projects`)

  console.log('Fetching blog slugs…')
  const { data: blogs, error: blogErr } = await cms
    .from('blogs')
    .select('slug')
    .not('slug', 'is', null)
    .order('published_date', { ascending: false })

  if (blogErr) console.warn('Could not fetch blogs:', blogErr.message)

  // Merge DB blog slugs with known hardcoded ones (dedup)
  const allBlogSlugs = [
    ...new Set([
      ...(blogs?.map(b => b.slug).filter(Boolean) ?? []),
      ...KNOWN_BLOG_SLUGS,
    ])
  ]

  console.log(`Found ${allBlogSlugs.length} blog posts`)

  // ── Build XML ──────────────────────────────────────────────────────────────
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
    '        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">',
    '',
    '  <!-- Generated by scripts/generate-sitemap.mjs on ' + new Date().toISOString() + ' -->',
    '',
    '  <!-- ━━━ STATIC PAGES ━━━ -->',
    ...STATIC.map(s => url(s.path, s.changefreq, s.priority)),
    '',
    '  <!-- ━━━ BLOG POSTS ━━━ -->',
    ...allBlogSlugs.map(slug => url(`/blog/${slug}`, 'never', '0.6')),
    '',
    '  <!-- ━━━ PROJECT PAGES (' + (projects?.length ?? 0) + ' total) ━━━ -->',
    ...(projects?.map(p => url(`/projects/${p.slug}`, 'monthly', '0.5')) ?? []),
    '',
    '</urlset>',
  ]

  writeFileSync(OUT_PATH, lines.join('\n'), 'utf8')
  console.log(`\n✓ Sitemap written to public/sitemap.xml`)
  console.log(`  ${STATIC.length} static pages`)
  console.log(`  ${allBlogSlugs.length} blog posts`)
  console.log(`  ${projects?.length ?? 0} project pages`)
  console.log(`  Total: ${STATIC.length + allBlogSlugs.length + (projects?.length ?? 0)} URLs`)
}

generate().catch(e => { console.error(e); process.exit(1) })
